#!/usr/bin/env python3
"""Generate nutation_data.go from Skyfield's nutation.npz.

Usage:
    python coord/generate_nutation_tables.py

Reads from ../python-skyfield/skyfield/data/nutation.npz and writes
coord/nutation_data.go with full IAU 2000A nutation coefficient tables.
"""

import os
import numpy as np

SKYFIELD_NPZ = os.path.join(os.path.dirname(__file__), '..', '..', 'python-skyfield', 'skyfield', 'data', 'nutation.npz')
OUTPUT = os.path.join(os.path.dirname(__file__), 'nutation_data.go')

def write_int_2d(f, name, arr, comment):
    rows, cols = arr.shape
    f.write(f'// {comment}\n')
    f.write(f'var {name} = [{rows}][{cols}]int{{\n')
    for row in arr:
        f.write('\t{' + ', '.join(str(int(v)) for v in row) + '},\n')
    f.write('}\n\n')

def write_float_2d(f, name, arr, comment):
    rows, cols = arr.shape
    f.write(f'// {comment}\n')
    f.write(f'var {name} = [{rows}][{cols}]float64{{\n')
    for row in arr:
        f.write('\t{' + ', '.join(repr(float(v)) for v in row) + '},\n')
    f.write('}\n\n')

def main():
    d = np.load(SKYFIELD_NPZ)

    with open(OUTPUT, 'w') as f:
        f.write('package coord\n\n')
        f.write('// Code generated by generate_nutation_tables.py from Skyfield nutation.npz. DO NOT EDIT.\n')
        f.write('// Source: IAU 2000A nutation model (IERS Conventions 2003).\n')
        f.write('// Luni-solar: 678 terms. Planetary: 687 terms.\n\n')

        write_int_2d(f, 'luniSolarNals', d['nals_t'],
            'luniSolarNals holds Delaunay argument multipliers for 678 luni-solar nutation terms.\n// Columns: nl, nl\', nF, nD, nOmega.')
        write_float_2d(f, 'luniSolarLonCoeffs', d['lunisolar_longitude_coefficients'],
            'luniSolarLonCoeffs holds dpsi (longitude) coefficients for 678 luni-solar terms.\n// Columns: sin, t*sin, cos. Units: 0.1 microarcseconds.')
        write_float_2d(f, 'luniSolarOblCoeffs', d['lunisolar_obliquity_coefficients'],
            'luniSolarOblCoeffs holds deps (obliquity) coefficients for 678 luni-solar terms.\n// Columns: cos, t*cos, sin. Units: 0.1 microarcseconds.')
        write_int_2d(f, 'planetaryNapl', d['napl_t'],
            'planetaryNapl holds argument multipliers for 687 planetary nutation terms.\n// Columns: nl, nl\', nF, nD, nOmega, nLMe, nLVe, nLE, nLMa, nLJ, nLSa, nLU, nLNe, nPa.')
        write_float_2d(f, 'planetaryLonCoeffs', d['nutation_coefficients_longitude'],
            'planetaryLonCoeffs holds dpsi (longitude) coefficients for 687 planetary terms.\n// Columns: sin, cos. Units: 0.1 microarcseconds.')
        write_float_2d(f, 'planetaryOblCoeffs', d['nutation_coefficients_obliquity'],
            'planetaryOblCoeffs holds deps (obliquity) coefficients for 687 planetary terms.\n// Columns: sin, cos. Units: 0.1 microarcseconds.')

    print(f'Wrote {OUTPUT}')
    # Verify sizes
    print(f'  luniSolarNals:      {d["nals_t"].shape}')
    print(f'  luniSolarLonCoeffs: {d["lunisolar_longitude_coefficients"].shape}')
    print(f'  luniSolarOblCoeffs: {d["lunisolar_obliquity_coefficients"].shape}')
    print(f'  planetaryNapl:      {d["napl_t"].shape}')
    print(f'  planetaryLonCoeffs: {d["nutation_coefficients_longitude"].shape}')
    print(f'  planetaryOblCoeffs: {d["nutation_coefficients_obliquity"].shape}')

if __name__ == '__main__':
    main()
